container:
  image: ghcr.io/cirruslabs/android-sdk:30
  cpu: 2
  memory: 8G
  kvm: true

check_android_task:
  install_emulator_script:
    npx envinfo || echo "Failed to run envinfo"
    MAESTRO_VERSION=1.30.4 curl -Ls 'https://get.maestro.mobile.dev' | bash
    sdkmanager --install "system-images;android-30;google_apis;x86"
  create_avd_script:
    echo no | avdmanager create avd --force
    -n emulator
    -k "system-images;android-30;google_apis;x86"
  start_avd_background_script:
    $ANDROID_HOME/emulator/emulator
    -avd emulator
    -no-audio
    -no-boot-anim
    -gpu swiftshader_indirect
    -no-snapshot
    -no-window
  wait_for_avd_script:
    adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 3; done; input keyevent 82'
  check_script:
    npx envinfo || echo "Failed to run envinfo"
    adb devices
    adb install app-release.apk
    (echo "-Attempt:1-" && $HOME/.maestro/bin/maestro test .maestro/ --env=APP_ID=com.retyui.myapp --output=report1.xml --format=junit) || (echo "-Attempt:2-" && sleep 20 && $HOME/.maestro/bin/maestro test .maestro/ --env=APP_ID=com.retyui.myapp --output=report2.xml --format=junit) || (echo "-Attempt:3-" && sleep 60 && $HOME/.maestro/bin/maestro test .maestro/ --env=APP_ID=com.retyui.myapp --output=report3.xml --format=junit) || (echo "-Failed-" && exit 1)

#
#
#run_android_e2e_task:
#  name: Android E2E (Circus CI) (API $API_LEVEL)
#  timeout_in: 30m
#  env:
#    matrix:
#      - API_LEVEL: 26
#      - API_LEVEL: 27
#      - API_LEVEL: 28
#      - API_LEVEL: 29
#      - API_LEVEL: 30
#      - API_LEVEL: 33
#    JAVA_TOOL_OPTIONS: -Xmx6g
#    GRADLE_OPTS: -Dorg.gradle.daemon=false -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process
#  container:
#    image: ghcr.io/cirruslabs/android-sdk:${API_LEVEL}
#    cpu: 4
#    memory: 12G
#    kvm: true
#
#  debug_system:
#    npx envinfo || echo "Failed to run envinfo"
#  install_maestro:
#    MAESTRO_VERSION=1.30.4 curl -Ls 'https://get.maestro.mobile.dev' | bash
#  create_device_script:
#    ARCH=x86_64
#    TARGET=default
#    if [[ $API_LEVEL -ge 30 ]]; then
#      TARGET=google_apis
#    fi
#    echo no | avdmanager create avd --force --name "emulator-${API_LEVEL}" --abi "${TARGET}/${ARCH}" --package "system-images;android-${API_LEVEL};${TARGET};${ARCH}"
#  start_emulator_background_script:
#    $ANDROID_HOME/emulator/emulator -avd "emulator-${API_LEVEL}" -no-audio -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none &
#  wait_for_emulator_script:
#    adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 3; done; input keyevent 82'
#  disable_animations_script: |
#    adb shell settings put global window_animation_scale 0.0
#    adb shell settings put global transition_animation_scale 0.0
#    adb shell settings put global animator_duration_scale 0.0
#  run_instrumented_tests_script:
#    npx envinfo || echo "Failed to run envinfo"
#
#    adb devices                 # verify emulator is running
#
#    adb install app-release.apk # install app
#
#    # Run e2e (3 attempts with different timeouts)
#    (echo "-Attempt:1-" && $HOME/.maestro/bin/maestro test .maestro/ --env=APP_ID=com.retyui.myapp --output=report1.xml --format=junit) || (echo "-Attempt:2-" && sleep 20 && $HOME/.maestro/bin/maestro test .maestro/ --env=APP_ID=com.retyui.myapp --output=report2.xml --format=junit) || (echo "-Attempt:3-" && sleep 60 && $HOME/.maestro/bin/maestro test .maestro/ --env=APP_ID=com.retyui.myapp --output=report3.xml --format=junit) || (echo "-Failed-" && exit 1)
#
#    # ^^^ I can't multiline operator `\` in `script` section as each line will be executed in a separate shell
